version: '3.8'

services:
  rag-chat-storage:
    build: .
    container_name: rag-chat-storage
    ports:
      - "8080:8080"
    environment:
      - API_KEY=${API_KEY:-secure-api-key-change-me}
      - SERVER_PORT=8080
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - RATE_LIMIT_RPM=${RATE_LIMIT_RPM:-100}
      - RATE_LIMIT_CAPACITY=${RATE_LIMIT_CAPACITY:-200}
      - CORS_ALLOWED_ORIGINS=${CORS_ALLOWED_ORIGINS:-*}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/v1/health/ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    networks:
      - ragchat-network

  # H2 Console (Development only)
  h2-console:
    image: oscarfonts/h2:latest
    container_name: h2-console
    ports:
      - "8082:8082"
    environment:
      - H2_OPTIONS=-web -webAllowOthers -tcp -tcpAllowOthers -browser
    restart: unless-stopped
    networks:
      - ragchat-network

  # Database management tool (Adminer)
  adminer:
    image: adminer:latest
    container_name: rag-chat-adminer
    ports:
      - "8081:8080"
    environment:
      - ADMINER_DEFAULT_SERVER=rag-chat-storage:8080
    restart: unless-stopped
    networks:
      - ragchat-network
    depends_on:
      - rag-chat-storage

networks:
  ragchat-network:
    driver: bridge

volumes:
  h2-data: